//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChocoAccounting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChocoAccounting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultra fast and simple home accounting.
        /// </summary>
        public static string About_AppSubtitle {
            get {
                return ResourceManager.GetString("About_AppSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choco Accounting is absolutely free to use. If you find this application useful please consider supporting its developers by making a donation..
        /// </summary>
        public static string About_ConsiderDonatingLabel {
            get {
                return ResourceManager.GetString("About_ConsiderDonatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by.
        /// </summary>
        public static string About_DevelopedBy {
            get {
                return ResourceManager.GetString("About_DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string About_DonateLink {
            get {
                return ResourceManager.GetString("About_DonateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNU General Public License:.
        /// </summary>
        public static string About_GNULabel {
            get {
                return ResourceManager.GetString("About_GNULabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is free software: you can redistribute it and/or modify
        ///it under the terms of the GNU General Public License as published by
        ///the Free Software Foundation, either version 3 of the License, or
        ///(at your option) any later version.
        ///            
        ///This program is distributed in the hope that it will be useful,
        ///but WITHOUT ANY WARRANTY; without even the implied warranty of
        ///MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        ///GNU General Public License for more details.
        ///
        ///You should hav [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About_GNUText {
            get {
                return ResourceManager.GetString("About_GNUText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        public static string About_SourceCodeLink {
            get {
                return ResourceManager.GetString("About_SourceCodeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Choco Accounting.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string About_WebsiteLink {
            get {
                return ResourceManager.GetString("About_WebsiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And finally.
        /// </summary>
        public static string AndFinally {
            get {
                return ResourceManager.GetString("AndFinally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And then.
        /// </summary>
        public static string AndThen {
            get {
                return ResourceManager.GetString("AndThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App config.
        /// </summary>
        public static string AppConfig {
            get {
                return ResourceManager.GetString("AppConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choco Accounting.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is in use, so it can&apos;t be deleted..
        /// </summary>
        public static string CannotDeleteDatabaseInUseText {
            get {
                return ResourceManager.GetString("CannotDeleteDatabaseInUseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database couldn&apos;t be found..
        /// </summary>
        public static string CannotDeleteDatabaseNotFoundText {
            get {
                return ResourceManager.GetString("CannotDeleteDatabaseNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item can&apos;t be deleted because it has related movements..
        /// </summary>
        public static string CannotDeleteRelatedMovementsText {
            get {
                return ResourceManager.GetString("CannotDeleteRelatedMovementsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, type a database name..
        /// </summary>
        public static string CannotLoadDatabaseNameRequiredText {
            get {
                return ResourceManager.GetString("CannotLoadDatabaseNameRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select a movement to modify..
        /// </summary>
        public static string CannotUpdateNoRowSelectedText {
            get {
                return ResourceManager.GetString("CannotUpdateNoRowSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemist&apos;s / Herbalist&apos;s.
        /// </summary>
        public static string ChemistsHerbalists {
            get {
                return ResourceManager.GetString("ChemistsHerbalists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing.
        /// </summary>
        public static string Clothing {
            get {
                return ResourceManager.GetString("Clothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all groups and subgroups.
        /// </summary>
        public static string CollapseToolTip {
            get {
                return ResourceManager.GetString("CollapseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communications.
        /// </summary>
        public static string Communications {
            get {
                return ResourceManager.GetString("Communications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy all.
        /// </summary>
        public static string CopyAll {
            get {
                return ResourceManager.GetString("CopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy all rows to clipboard.
        /// </summary>
        public static string CopyAllToolTip {
            get {
                return ResourceManager.GetString("CopyAllToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to create default categories on this database? They will be created with the currently selected language..
        /// </summary>
        public static string CreateDefaultCategoriesQuestion {
            get {
                return ResourceManager.GetString("CreateDefaultCategoriesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This database is already loaded..
        /// </summary>
        public static string DatabaseAlreadyLoadedText {
            get {
                return ResourceManager.GetString("DatabaseAlreadyLoadedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name.
        /// </summary>
        public static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a date.
        /// </summary>
        public static string DataPickerWatermark {
            get {
                return ResourceManager.GetString("DataPickerWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date from.
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date to.
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database deleted..
        /// </summary>
        public static string DeleteDatabaseCompleteText {
            get {
                return ResourceManager.GetString("DeleteDatabaseCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this database?.
        /// </summary>
        public static string DeleteDatabaseQuestionText {
            get {
                return ResourceManager.GetString("DeleteDatabaseQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure yo want to delete this record?.
        /// </summary>
        public static string DeleteRecordQuestionText {
            get {
                return ResourceManager.GetString("DeleteRecordQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donations.
        /// </summary>
        public static string Donations {
            get {
                return ResourceManager.GetString("Donations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        public static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (English).
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        public static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all groups and subgroups.
        /// </summary>
        public static string ExpandToolTip {
            get {
                return ResourceManager.GetString("ExpandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        public static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered item already exists..
        /// </summary>
        public static string FieldMustBeUniqueText {
            get {
                return ResourceManager.GetString("FieldMustBeUniqueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field has an invalid format. It must be a numeric value..
        /// </summary>
        public static string FieldNotNumericToolTipText {
            get {
                return ResourceManager.GetString("FieldNotNumericToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field is empty. This is a required field..
        /// </summary>
        public static string FieldRequiredToolTipText {
            get {
                return ResourceManager.GetString("FieldRequiredToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some fields aren&apos;t properly filled..
        /// </summary>
        public static string FieldsValidationFailedText {
            get {
                return ResourceManager.GetString("FieldsValidationFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering.
        /// </summary>
        public static string Filtering {
            get {
                return ResourceManager.GetString("Filtering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fines.
        /// </summary>
        public static string Fines {
            get {
                return ResourceManager.GetString("Fines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        public static string Fuel {
            get {
                return ResourceManager.GetString("Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galician (Galego).
        /// </summary>
        public static string Galician {
            get {
                return ResourceManager.GetString("Galician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gifts.
        /// </summary>
        public static string Gifts {
            get {
                return ResourceManager.GetString("Gifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by.
        /// </summary>
        public static string GroupBy {
            get {
                return ResourceManager.GetString("GroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        public static string Grouping {
            get {
                return ResourceManager.GetString("Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurances.
        /// </summary>
        public static string Insurances {
            get {
                return ResourceManager.GetString("Insurances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        public static string Internet {
            get {
                return ResourceManager.GetString("Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leisure.
        /// </summary>
        public static string Leisure {
            get {
                return ResourceManager.GetString("Leisure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loans.
        /// </summary>
        public static string Loans {
            get {
                return ResourceManager.GetString("Loans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage databases.
        /// </summary>
        public static string ManageDatabases {
            get {
                return ResourceManager.GetString("ManageDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manteinance and repairs.
        /// </summary>
        public static string ManteinanceAndRepairs {
            get {
                return ResourceManager.GetString("ManteinanceAndRepairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string MessageBoxAttentionText {
            get {
                return ResourceManager.GetString("MessageBoxAttentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage.
        /// </summary>
        public static string Mortgage {
            get {
                return ResourceManager.GetString("Mortgage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movement(s).
        /// </summary>
        public static string MovementCount {
            get {
                return ResourceManager.GetString("MovementCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value doesn&apos;t exist, so it will be created..
        /// </summary>
        public static string NewDataToolTipText {
            get {
                return ResourceManager.GetString("NewDataToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entity.
        /// </summary>
        public static string NoEntity {
            get {
                return ResourceManager.GetString("NoEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No person.
        /// </summary>
        public static string NoPerson {
            get {
                return ResourceManager.GetString("NoPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subcategory.
        /// </summary>
        public static string NoSubcategory {
            get {
                return ResourceManager.GetString("NoSubcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other incomes.
        /// </summary>
        public static string OtherIncomes {
            get {
                return ResourceManager.GetString("OtherIncomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other shopping.
        /// </summary>
        public static string OtherShopping {
            get {
                return ResourceManager.GetString("OtherShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pend..
        /// </summary>
        public static string PendingAbbreviation {
            get {
                return ResourceManager.GetString("PendingAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q. w/o tax.
        /// </summary>
        public static string QuantityWithoutTax {
            get {
                return ResourceManager.GetString("QuantityWithoutTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular shopping.
        /// </summary>
        public static string RegularShopping {
            get {
                return ResourceManager.GetString("RegularShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rentals.
        /// </summary>
        public static string Rentals {
            get {
                return ResourceManager.GetString("Rentals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salaries.
        /// </summary>
        public static string Salaries {
            get {
                return ResourceManager.GetString("Salaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        public static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish (Español).
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory.
        /// </summary>
        public static string Subcategory {
            get {
                return ResourceManager.GetString("Subcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes.
        /// </summary>
        public static string Taxes {
            get {
                return ResourceManager.GetString("Taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax %.
        /// </summary>
        public static string TaxPercentage {
            get {
                return ResourceManager.GetString("TaxPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolls.
        /// </summary>
        public static string Tolls {
            get {
                return ResourceManager.GetString("Tolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total w/o tax.
        /// </summary>
        public static string TotalWithoutTax {
            get {
                return ResourceManager.GetString("TotalWithoutTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation.
        /// </summary>
        public static string Transportation {
            get {
                return ResourceManager.GetString("Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vet.
        /// </summary>
        public static string Vet {
            get {
                return ResourceManager.GetString("Vet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View existing.
        /// </summary>
        public static string ViewExisting {
            get {
                return ResourceManager.GetString("ViewExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        public static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
